import { Question } from "./types.js";

const base = (
  id: string,
  text: string,
  category: Question["category"],
): Question => ({ id, text, category, source: "predefined" });

export const predefinedQuestions: Question[] = [
  base("q1", "What is his favorite comfort food?", "safe"),
  base("q2", "What movie can he rewatch forever?", "safe"),
  base("q3", "What hobby relaxes him the most?", "safe"),
  base("q4", "What city does he most want to visit next?", "safe"),
  base("q5", "What is his usual coffee order?", "safe"),
  base("q6", "What song gets him instantly hyped?", "safe"),
  base("q7", "What is his favorite day of the week and why?", "safe"),
  base("q8", "What time does he usually wake up on weekends?", "safe"),
  base("q9", "What app does he open first in the morning?", "safe"),
  base("q10", "What snack disappears fastest at home?", "safe"),
  base("q11", "What is his go-to takeout order?", "safe"),
  base("q12", "What board game or game does he always pick?", "safe"),
  base("q13", "What weather makes him happiest?", "safe"),
  base("q14", "What does he usually procrastinate the most?", "safe"),
  base("q15", "What phrase does he say when he is stressed?", "fun"),
  base("q16", "What tiny thing annoys him instantly?", "fun"),
  base("q17", "What weird habit does he have at home?", "fun"),
  base("q18", "What excuse does he use when he is late?", "fun"),
  base("q19", "What would he buy first if he won the lottery?", "fun"),
  base("q20", "What is his most used emoji?", "fun"),
  base("q21", "What does he pretend to hate but secretly likes?", "fun"),
  base("q22", "What is his most dramatic overreaction topic?", "fun"),
  base("q23", "What is his funniest kitchen fail?", "fun"),
  base("q24", "What is his classic dance move?", "fun"),
  base("q25", "What is his guilty pleasure TV show?", "fun"),
  base("q26", "What is the most random thing in his pockets?", "fun"),
  base("q27", "What talent does he think he has but probably does not?", "fun"),
  base("q28", "What topic can he rant about for 10 minutes?", "fun"),
  base("q29", "What nickname would embarrass him most?", "spicy"),
  base("q30", "What was his most awkward date moment?", "spicy"),
  base("q31", "What is his most irrational fear?", "spicy"),
  base("q32", "What bad habit is he always trying to quit?", "spicy"),
  base("q33", "What is his most embarrassing autocorrect fail?", "spicy"),
  base(
    "q34",
    "What fashion choice from his past should stay in the past?",
    "spicy",
  ),
  base("q35", "What would he absolutely panic about losing?", "spicy"),
  base("q36", "What is his worst karaoke song choice?", "spicy"),
  base("q37", "What silly lie did he tell as a kid?", "spicy"),
  base("q38", "What is his funniest jealous moment?", "spicy"),
  base("q39", "What is his most chaotic vacation story?", "spicy"),
  base("q40", "What is the cringiest thing he still says?", "spicy"),
  base("q41", "What tiny superstition does he secretly follow?", "fun"),
  base("q42", "What is his default answer when he has no clue?", "fun"),
  base("q43", "What chore does he avoid until the last second?", "safe"),
  base("q44", "What is his favorite midnight snack combination?", "safe"),
  base("q45", "What is his most dramatic travel complaint?", "spicy"),
];
